CommerceListMVC/ViewComponents/CategoryNavViewComponent.cs
using Business.Abstract;
using DataAccess.Concreate;
using Entitites.Concrete.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CommerceListMVC.ViewComponents
{
    public class CategoryNavViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;
        public CategoryNavViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            IEnumerable<CategoryListViewModel> categoryList = _categoryService.GetAll().Select(c => new CategoryListViewModel()
            {
                CategoryName = c.CategoryName,
                CategoryID = c.CategoryID,
            }).ToList();
            return View(categoryList);

        }
    }
}

CommerceListMVC/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CommerceListMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CommerceListMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="List">CommerceListMVC</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">



                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Product" asp-action="ProductControl">Ürün Kontrol Paneli</a>
                            
                        </li>
                        <li class="nav-item"> <a class="nav-link" asp-controller="Category" asp-action="CategoryControl">Kategori Kontrol Paneli</a></li>
                        <li class="nav-item"> <a class="nav-link" asp-action="Users" asp-controller="Admin">Kullanıcılar</a></li>
                        <li class="nav-item"><a class="btn btn-warning-outline" asp-area="" asp-controller="User" asp-action="Logout" asp-route-returnUrl="/User/Login">Logout</a></li>
                       
                       
                        
                    </ul>

                </div>
            </div>
        </nav>



    </header>



    <div class="container">

      

          

            <div>
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>


     

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CommerceListMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CommerceListMVC/Views/Shared/_Layout.cshtml
@using Entities.Concreate.ViewModels;
@using Microsoft.AspNetCore.Http;

@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CommerceListMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CommerceListMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="List">CommerceListMVC</a>
             
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                     
                   
              
                        <li class="nav-item">
                            <a class="btn btn-warning-outline" asp-area="" asp-controller="CommerceList" asp-action="List" >Alış-Veriş Listelerim</a>
                            <a class="btn btn-warning-outline" asp-area="" asp-controller="User" asp-action="Logout" asp-route-returnUrl="/User/Login">Logout</a>
                         
                        </li>
                    </ul>
                 
                </div>
            </div>
        </nav>
      
        
   
    </header>
   
  

    <div class="container-fluid">
  
        <div class="row">

                <div class="col-3">
                    <ul class="list-group">@await Component.InvokeAsync("CategoryNav")</ul>
                </div>
          
        
            <div class="col-6">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
             </div>
          
          
          
   
        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CommerceListMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CommerceListMVC/Views/Shared/_LoginRegisterLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - CommerceListMVC</title>
        <meta charset="utf-8" />

    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CommerceListMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container-sm">
        <div class="row mx-auto my-5 d-flex justify-content-center">
            <div class="col-3 ">
                @RenderBody()
            </div>
        </div>
     
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>